spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weatherdb
    username: root
    password: Fateavernous123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: ERROR
  file.path: D:/logs
  file.name: ${logging.file.path}/weatherLog.log



